import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/components/Header';
import { Navigation } from '@/components/Navigation';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  preload: true,
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative flex min-h-screen">
          <aside className="hidden md:flex flex-col border-r border-[#2684FF]/10">
            <Navigation />
          </aside>
          <div className="flex flex-col flex-1">
            <Header />
            <div className='overflow-auto h-screen'>
              <main className="flex-1 p-6 mb-12">{children}</main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
